INSERT INTO USUARIO(DS_EMAIL, DS_SENHA, NM_USUARIO, NR_TELEFONE) VALUES('peterebond@gmail.com', '$2a$10$sFKmbxbG4ryhwPNx/l3pgOJSt.fW1z6YcUnuE2X8APA/Z3NI/oSpq', 'PETER EDWARD BOND JUNIOR', 11966706720);

INSERT INTO PERFIL (ID_PERFIL, DS_PERFIL) VALUES (1, 'ADMINISTRADOR');
INSERT INTO PERFIL (ID_PERFIL, DS_PERFIL) VALUES (2, 'CLIENTE');

INSERT INTO USUARIO_PERFIS (USUARIO_ID_USUARIO, PERFIS_ID_PERFIL) VALUES (1, 2);

INSERT INTO FINANC_MES (DS_DETALHADA_MES, DS_FINANC_MES, VL_TOT_CONTAS_MES, USUARIO_ID_USUARIO) VALUES ('IPVA 4/5 - Roberta vai pagar 200,00  Ver contas de santos  Cobrar conta dos idiotas que vieram em casa', 'Jun - 2022', 13500, 1);

INSERT INTO FINANC_MES_CONTA (DS_FINANC_MES_CONTA, DT_VENCIMENTO, STATUS, VL_FINANC_MES_CONTA, FINANC_MES_ID_FINANC_MES) VALUES ('Condominio / Fundo Reserva', '2022-05-10', 'NAO_PAGO', 1200, 1);
INSERT INTO FINANC_MES_CONTA (DS_FINANC_MES_CONTA, DT_VENCIMENTO, STATUS, VL_FINANC_MES_CONTA, FINANC_MES_ID_FINANC_MES) VALUES ('IPTU 4/10', '2022-05-10', 'NAO_PAGO', 503, 1);
INSERT INTO FINANC_MES_CONTA (DS_FINANC_MES_CONTA, DT_VENCIMENTO, STATUS, VL_FINANC_MES_CONTA, FINANC_MES_ID_FINANC_MES) VALUES ('IPVA 4/5', '2022-05-14', 'NAO_PAGO', 412, 1);
INSERT INTO FINANC_MES_CONTA (DS_FINANC_MES_CONTA, DT_VENCIMENTO, STATUS, VL_FINANC_MES_CONTA, FINANC_MES_ID_FINANC_MES) VALUES ('Apartamento', '2022-05-17', 'NAO_PAGO', 4900, 1);
INSERT INTO FINANC_MES_CONTA (DS_FINANC_MES_CONTA, DT_VENCIMENTO, STATUS, VL_FINANC_MES_CONTA, FINANC_MES_ID_FINANC_MES) VALUES ('Água', '2022-05-25', 'NAO_PAGO', 200, 1);

INSERT INTO FINANC_MES_CONTA_PARC (DS_FINANC_MES_CONTA_PARC, NR_PARCELA_ATUAL, NR_TOT_PARCELA, VL_PARCELA, FINANC_MES_ID_FINANC_MES) VALUES ('Magalu: 6/10', 10, 10, 90, 1);
INSERT INTO FINANC_MES_CONTA_PARC (DS_FINANC_MES_CONTA_PARC, NR_PARCELA_ATUAL, NR_TOT_PARCELA, VL_PARCELA, FINANC_MES_ID_FINANC_MES) VALUES ('Extra: 6/9', 6, 9, 48, 1);
INSERT INTO FINANC_MES_CONTA_PARC (DS_FINANC_MES_CONTA_PARC, NR_PARCELA_ATUAL, NR_TOT_PARCELA, VL_PARCELA, FINANC_MES_ID_FINANC_MES) VALUES ('Poltrona 5/8', 8, 8, 110, 1);
INSERT INTO FINANC_MES_CONTA_PARC (DS_FINANC_MES_CONTA_PARC, NR_PARCELA_ATUAL, NR_TOT_PARCELA, VL_PARCELA, FINANC_MES_ID_FINANC_MES) VALUES ('Oculos 5/6', 5, 6, 109.50, 1);
INSERT INTO FINANC_MES_CONTA_PARC (DS_FINANC_MES_CONTA_PARC, NR_PARCELA_ATUAL, NR_TOT_PARCELA, VL_PARCELA, FINANC_MES_ID_FINANC_MES) VALUES ('MAGAZINELUIZA 9/10', 9, 10, 75.64, 1);
INSERT INTO FINANC_MES_CONTA_PARC (DS_FINANC_MES_CONTA_PARC, NR_PARCELA_ATUAL, NR_TOT_PARCELA, VL_PARCELA, FINANC_MES_ID_FINANC_MES) VALUES ('MercPag*TECNOLOGIA 5/12 ', 5, 12, 14.50, 1);

--INSERT INTO TOPICO(titulo, mensagem, data_criacao, status, autor_id, curso_id) VALUES('Dúvida', 'Erro ao criar projeto', '2019-05-05 18:00:00', 'NAO_RESPONDIDO', 1, 1);
--INSERT INTO TOPICO(titulo, mensagem, data_criacao, status, autor_id, curso_id) VALUES('Dúvida 2', 'Projeto não compila', '2019-05-05 19:00:00', 'NAO_RESPONDIDO', 1, 1);
--INSERT INTO TOPICO(titulo, mensagem, data_criacao, status, autor_id, curso_id) VALUES('Dúvida 3', 'Tag HTML', '2019-05-05 20:00:00', 'NAO_RESPONDIDO', 1, 2);
